### ISSUE TITLE
Huge problem with data URIs

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [alexo/wro4j#118]
It is actually the mapping of a simple CSS with cssMin minification.

wro.properties:

```
preProcessors=lessCss
postProcessors=cssMin,uglifyJs
```

This:

``` CSS
.test {
  background-image: url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");
}
```

Compiles into this:

``` CSS
.test{background-image:url("data:image/gif;}
```

But should compile into this:

``` CSS
.test{background-image:url("data:image/gif;;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7")}
```
