### ISSUE TITLE
KeepCopyrightDecorator doesn't take effect

### ISSUE THREAD

**Issue by dtrunk90** [alexo/wro4j#124]
web.xml Filter:

``` xml
<filter>
        <filter-name>WebResourceOptimizer</filter-name>
        <filter-class>ro.isdc.wro.http.WroFilter</filter-class>
        <init-param>
            <param-name>managerFactoryClassName</param-name>
            <param-value>com.example.web.wro.manager.MyWroManagerFactory</param-value>
        </init-param>
    </filter>
```

MyWroManagerFactory:

``` java
public class MyWroManagerFactory extends BaseWroManagerFactory {
    @Override
    protected ProcessorsFactory newProcessorsFactory() {
        return new SimpleProcessorsFactory()
                .addPreProcessor(new CssUrlRewritingProcessor())
                .addPreProcessor(new CssImportPreProcessor())
                .addPreProcessor(new SemicolonAppenderPreProcessor())
                .addPreProcessor(new LessCssProcessor())
                .addPostProcessor(CopyrightKeeperProcessorDecorator.decorate(new CssMinProcessor()))
                .addPostProcessor(CopyrightKeeperProcessorDecorator.decorate(new JSMinProcessor()));
    }
}
```

wro.xml:

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<groups xmlns="http://www.isdc.ro/wro">

    <group name="global">
        <css>/resources/css/reset.css</css>
        <js minimize="false">/resources/js/jquery/jquery-2.0.1.min.js</js>
    </group>

</groups>
```

Resulting global.css:

``` css
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{border:0;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline;}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block;}body{line-height:1;}ol,ul{list-style:none;}blockquote,q{quotes:none;}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none;}table{border-collapse:collapse;border-spacing:0;}
```

There should be the following copyright notice at the top of the file:

``` css
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/
```
