### ISSUE TITLE
Less Variables in url() gets rewritten

### ISSUE THREAD

**Issue by dtrunk90** [alexo/wro4j#136]
I would like to do something like this:

``` less
@gStaticMap: ~'http://maps.googleapis.com/maps/api/staticmap?size=640x640&zoom=15&markers=...';

#interactiveMap {
    background-image: url('@{gStaticMap}');
}
```

This is the result:

``` css
#interactiveMap {
    background-image: url("../../resources/css/http://maps.googleapis.com/maps/api/staticmap?size=640x640&zoom=15&markers=...");
}
```

My wro configuration (only processors):

``` properties
preProcessors=cssUrlRewriting,cssImport,semicolonAppender,lessCss.less
postProcessors=jsMin,cssMinJawr
```
