### ISSUE TITLE
CSS Import Processor not handling media specified in @import

### ISSUE THREAD

**Issue by gulench** [alexo/wro4j#138]
Consider the following CSS files:

**screen.css**:

``` css
body {
  background: white;
}
```

**print.css**:

``` css
body {
  background: none;
}
```

**all.css**:

``` css
@import 'screen.css' screen, projection;
@import 'print.css' print;
```

The generated CSS file for all.css does not appropriately contain the media specified in the @import lines; resulting CSS file is shown below:

``` css
body {
  background: white;
}
body {
  background: none;
} screen, projection;
 print;
```
