### ISSUE TITLE
cssUrlRewriting wrong url with wro4j 1.7.3

### ISSUE THREAD

**Issue by chatellier** [alexo/wro4j#173]
Hi,

In current wro4j version 1.7.3, cssUrlRewriting rewrite url like this (jquery-ui):

``` css
.ui-widget-header .ui-icon {
    background-image: url("/myapp/wro/wroAPI/wroResources?id=classpath:META-INF/resources/nuiton-js-jquery-ui/css/base/images/ui-icons_222222_256x240.png");
}
```

This link to 404 error. Temporary workarround is to downgrade to version 1.7.0 that generates following correct urls:

``` css
.ui-widget-header .ui-icon {
    background-image: url("/myapp/wro/wroResources?id=classpath:META-INF/resources/nuiton-js-jquery-ui/css/base/images/ui-icons_222222_256x240.png");
}
```
