### ISSUE TITLE
[less-processor] Twitter Bootstrap 2.0 invalid

### ISSUE THREAD

**Issue by BowlingX** [alexo/wro4j#58]
Hey, 
Bootstrap does not compile well with wro4j's current less-processor implementation. 
I have issues with code where functions from "mixins.less" are invoked:

e.g.: tooltip.less is compiled as:

``` css
//[...]
.tooltip-arrow {
    bottom: 0;
    left: 50%;
    margin-left: -5px;
    border-left: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-right: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-top: 5px solid #000
}

.tooltip.left .tooltip-arrow {
    top: 50%;
    right: 0;
    margin-top: -5px;
    border-top: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-bottom: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-left: 5px solid #000
}

.tooltip.bottom .tooltip-arrow {
    top: 0;
    left: 50%;
    margin-left: -5px;
    border-left: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-right: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-bottom: 5px solid #000
}

.tooltip.right .tooltip-arrow {
    top: 50%;
    left: 0;
    margin-top: -5px;
    border-top: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-bottom: 5px solid #NaNbbaaNaN00NaN00NaN00NaN00NaN;
    border-right: 5px solid #000
}

.tooltip-inner {
    max-width: 200px;
    padding: 3px 8px;
    color: #fff;
    text-align: center;
    text-decoration: none;
    background-color: #000;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px
}

//[...]
```

it seems like some variables could not resolved correctly.
I tested the latest version from Bootstrap and wro4j 1.4.7.
